Exoduss/urls.py
from django.contrib import admin
from django.urls import path, include
from singup import views as user_views
from rest_framework import routers
from api.views import *


router = routers.DefaultRouter()
router.register(r'trips', TripsViewSet, "trips")
router.register(r'votes', VotesViewSet, "response")
router.register(r'recent', RecentViewSet, "recent")
router.register(r'users', UserListViewSet, "users")
router.register(r'follow', FollowViewSet, "follow")
router.register(r'home_trips', TripsHomeViewSet, "home_trips")
router.register(r'home_agencies', AgenciesHomeViewSet, "home_agencies")
router.register(r'interests', InterestsModelViewSet, 'interests')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('agencies/', include('agencies.urls')),
    path('', include('home.urls')),
    path('trips/', include('trips.urls')),
    path('votes/', include('votes.urls')),
    path('register/', user_views.register, name='register'),
    path('forms/', include('singup.urls')),
    path('user/', include('user.urls')),
    path('api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/user/<int:pk>/', UserView.as_view()),
    path('api/userpass/<int:pk>/', UserPasswordView.as_view()),
    path('api/user/login/', UserLoginView.as_view()),
    path('api/interests/<int:pk>', InterestedVoteViewSet.as_view()),
    path('api/trips/<int:pk>', TripView.as_view()),
    path('api/users/<int:pk>', OneUserView.as_view()),
    path('api/', include(router.urls)),
]

agencies/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main, name='agency_main'),
    path('a', views.agencies, name='agencies'),
    path('a/', include('agency.urls')),
    path('follow', views.follow, name='follow'),
    path('unfollow', views.un_follow, name='unfollow'),
]

agency/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('<str:agency_name>', views.agency, name='agency'),
    path('vote', views.agency_votes, name='agency_votes'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('', views.home, name='home'),
        path('signup', views.sign_up, name='signup'),
        path('signin', views.sign_in, name='signin'),

]

agencies/models.py
from django.db import models


class Agencies(models.Model):
    agency_id = models.AutoField(db_column='Agency_id', primary_key=True)
    name = models.CharField(max_length=45)
    address = models.CharField(db_column='Address', max_length=45)
    e_mail = models.CharField(db_column='E-mail', max_length=45)
    commercial_id = models.CharField(max_length=45)
    bio = models.CharField(max_length=45)
    promo_code = models.CharField(db_column='promo-code', max_length=45)
    rate = models.CharField(db_column='Rate', max_length=45)
    photo_url = models.TextField(db_column='photo_URL')

    class Meta:
        managed = False
        db_table = 'agencies'


class Phones(models.Model):
    agency = models.ForeignKey(Agencies, models.DO_NOTHING, db_column='Agency_id')
    phone = models.CharField(max_length=13, primary_key=True)

    class Meta:
        managed = False
        db_table = 'phones'
        unique_together = (('agency', 'phone'),)


class Users(models.Model):
    user_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    e_mail = models.CharField(db_column='e-mail', max_length=45, blank=True, null=True)
    phone = models.CharField(max_length=11, blank=True, null=True)
    city = models.CharField(max_length=45)

    class Meta:
        managed = False
        db_table = 'users'


class Follows(models.Model):
    user = models.ForeignKey('Users', models.DO_NOTHING, primary_key=True)
    agency = models.ForeignKey(Agencies, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'follows'
        unique_together = (('user', 'agency'),)

agency/models.py
from django.db import models


class Agencies(models.Model):
    agency_id = models.AutoField(db_column='Agency_id', primary_key=True)
    name = models.CharField(max_length=45)
    address = models.CharField(db_column='Address', max_length=45)
    e_mail = models.CharField(db_column='E-mail', max_length=45)
    commercial_id = models.CharField(max_length=45)
    bio = models.CharField(max_length=45)
    promo_code = models.CharField(db_column='promo-code', max_length=45)
    rate = models.CharField(db_column='Rate', max_length=45)
    photo_url = models.TextField(db_column='photo_URL')

    class Meta:
        managed = False
        db_table = 'agencies'


class Phones(models.Model):
    agency = models.ForeignKey(Agencies, models.DO_NOTHING, db_column='Agency_id')
    phone = models.CharField(max_length=13, primary_key=True)

    class Meta:
        managed = False
        db_table = 'phones'
        unique_together = (('agency', 'phone'),)


class Users(models.Model):
    user_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    phone = models.CharField(max_length=11, blank=True, null=True)
    city = models.CharField(max_length=45)

    class Meta:
        managed = False
        db_table = 'users'


class Follows(models.Model):
    user = models.ForeignKey('Users', models.DO_NOTHING, primary_key=True)
    agency = models.ForeignKey(Agencies, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'follows'
        unique_together = (('user', 'agency'),)


class Trips(models.Model):
    trip_id = models.AutoField(db_column='Trip_id', primary_key=True)  # Field name made lowercase.
    agency = models.ForeignKey(Agencies, models.DO_NOTHING, db_column='Agency_id')  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=50)  # Field name made lowercase.
    from_location = models.CharField(db_column='From_Location', max_length=45)  # Field name made lowercase.
    to_location = models.CharField(db_column='To_Location', max_length=45)  # Field name made lowercase.
    date_from = models.DateTimeField(db_column='Date_From')  # Field name made lowercase.
    date_to = models.DateTimeField(db_column='Date_To')  # Field name made lowercase.
    deadline = models.DateTimeField(db_column='Deadline')  # Field name made lowercase.
    meals = models.CharField(db_column='Meals', max_length=45)  # Field name made lowercase.
    price = models.FloatField(db_column='Price')  # Field name made lowercase.
    description = models.TextField(db_column='Description')  # Field name made lowercase.
    views = models.PositiveIntegerField(db_column='Views')  # Field name made lowercase.
    rate = models.FloatField(db_column='Rate')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'trips'


class TripPhotos(models.Model):
    trip = models.ForeignKey('Trips', models.DO_NOTHING, db_column='Trip_id', primary_key=True)
    url = models.TextField(db_column='URL')

    class Meta:
        managed = False
        db_table = "trip_photos'"


class GoingTo(models.Model):
    user = models.ForeignKey('Users', models.DO_NOTHING, db_column='User_id', primary_key=True)
    trip = models.ForeignKey('Trips', models.DO_NOTHING, db_column='Trip_id')

    class Meta:
        managed = False
        db_table = 'going_to'
        unique_together = (('user', 'trip'),)

class Vote(models.Model):
    vote_id = models.AutoField(db_column='Vote_id', primary_key=True)  # Field name made lowercase.
    agency = models.ForeignKey(Agencies, models.DO_NOTHING, db_column='Agency_id')  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=45)  # Field name made lowercase.
    description = models.TextField(db_column='Description')  # Field name made lowercase.
    photo_url = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'vote'

agencies/views.py
from django.shortcuts import render, redirect
from .models import *


def agencies(request):
    company = Agencies.objects.all()
    query = request.GET.get("q")
    if query:
        company = Agencies.objects.filter(name__icontains=query)
    if "user_id" in request.session != None:
        user_id = request.session['user_id']
        follows = Follows.objects.filter(user_id=user_id)
        followed = get_follow(company, follows)
        obj = {
            "agency": company,
            "follow": followed,
        }

    else:

        obj = {
            "agency": company,
        }
    return render(request, "agencies.html", obj)


def main(request):
    agencies(request)
    return render(request, 'main.html')


def follow(request):
    if request.method == "POST":
        user_id = request.session['user_id']
        agency_id = request.POST['btnFollow']
        Follows.objects.create(user_id=user_id, agency_id=agency_id)
    return redirect(agencies)


def un_follow(request):
    if request.method == "POST":
        user_id = request.session['user_id']
        agency_id = request.POST['btnUnfollow']
        Follows.objects.filter(user_id=user_id, agency_id=agency_id).delete()
    return redirect(agencies)


def get_follow(agencies_follow, follows):
    agency_follow = []
    for a in agencies_follow:
        followed = False
        if follows.filter(agency_id=a.agency_id).exists():
            followed = True
        following = {
                'agency': a.agency_id,
                'follow': followed
            }
        agency_follow.append(following)
    return agency_follow

agency/views.py
import datetime
from django.shortcuts import render
from .models import *


def agency(request, agency_name):
    agency_id = Agencies.objects.get(name__icontains=agency_name).agency_id

    q = request.GET.get('button')

    if q == 'available':
        obj = available(agency_id)
        return render(request, "agency_trips.html", obj)

    elif q == 'votes':
        obj = agency_votes(agency_id)
        return render(request, 'agency_votes.html', obj)

    elif q == 'account':
        obj = agency_info(agency_id)
        return render(request, 'agency_info.html', obj)

    else:
        obj = history(agency_id)
        return render(request, "agency_trips.html", obj)


def available(agency_id):
    company = Agencies.objects.get(agency_id=agency_id)
    trip = Trips.objects.filter(agency_id=agency_id, deadline__gt=datetime.date.today())
    for t in trip:
        t.duration = t.date_to.date() - t.date_from.date()

    active = 'active'
    inactive = 'inactive'
    obj = {
        "agency": company,
        "trips": trip,
        "history": inactive,
        "available": active,
    }
    return obj


def history(agency_id):
    company = Agencies.objects.get(agency_id=agency_id)
    trip = Trips.objects.filter(agency_id=agency_id, deadline__lt=datetime.date.today()).order_by('deadline')
    for t in trip:
        t.duration = t.date_to.date() - t.date_from.date()

    active = 'active'
    inactive = 'inactive'
    obj = {
        "agency": company,
        "trips": trip,
        "history": active,
        "available": inactive,
    }
    return obj


def agency_votes(agency_id):
    company = Agencies.objects.filter(agency_id=agency_id)[0]
    votes = Vote.objects.filter(agency_id=agency_id)
    obj = {
        "votes": votes,
        "agency": company,
    }
    return obj


def agency_info(agency_id):
    company = Agencies.objects.get(agency_id=agency_id)
    obj = {
        "agency": company,
    }
    return obj

agency/templates/agency_info.html
{% extends 'agency.html' %}
{% block content %}
    <div id="tab3" class="tab-details active">
        <div class="user-info">
            <img src="{{ agency.photo_url }}" alt="">
            <form class="" method="post">
                <div>
                    <label>Agency Name</label>
                    <h3>{{ agency.name }}</h3>
                </div>
                <div>
                    <label>bio</label>
                    <h3>{{ agency.bio }}</h3>
                </div>
                <div>
                    <label>address</label>
                    <h3>{{ agency.address }}</h3>
                </div>
                <div>
                    <label>e-mail</label>
                    <h3>{{ agency.e_mail }}</h3>
                </div>
                <div>
                    <label>phone</label>
                        <ul>
                            {% for t in agency.phones_set.all %}
                                <h3>{{ t.phone }}</h3>
                            {% endfor %}
                        </ul>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

agency/templates/agency_trips.html
{% extends 'agency.html' %}
{% block content %}
    <div id="tab1" class="tab-details active">
        <div class="my-trips-tabs">
            <form method="get" action="">
                <button class="{{ history }}" data-id="history" value="history" type="submit" name="button">history</button>
            </form>
            <form method="get" action="">
                <button class="{{ available }}" data-id="saved" value="available" type="submit" name="button">available</button>
            </form>
        </div>
        <div>
            <div id="history" class="post-contain active">
                {% for t in trips %}
                    <a href="trip-page.html">
                        <div class="post">
                            <div class="post-img">
                                <img src="{{ t.tripphotos_set.all.0.url }}" alt="">
                                <div class="overlay">
                                    <button class="learn-more" type="button" name="button">review</button>
                                </div>
                            </div>
                            <div class="post-info">
                                <h2>{{ t.name }}</h2>
                                <h2>{{ agency.name }}</h2>
                                <h4><span>Price</span>{{ t.price }}</h4>
                                <h4><span>date</span>{{ t.date_from|date:"d/m/Y"}}</h4>
                                <h4><span>duration</span> {{ t.duration.days }} Days</h4>
                                <h4><span>meals</span> {{ t.meals }}</h4>
                                <h4><span><i class="fas fa-plane"></i>going</span>{{ t.goingto_set.count }}</h4>
                                <h4><span><i class="far fa-eye"></i>views</span>{{ t.views }}</h4>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

agency/templates/agency_votes.html
{% extends 'agency.html' %}
{% block content %}
    <div id="tab2" class="tab-details active">

            {% for vote in votes %}
                <a href="vote-page.html">
                <div class="post">
                <div class="post-img">
                    <img src="{{ vote.photo_url }}" alt="">
                    <div class="overlay">
                        <button class="learn-more" type="button" name="button">agency page</button>
                    </div>
                </div>
                <div class="post-info">
                    <h2>{{ vote.name }}</h2>
                    <div class="clear"></div>
                    <p>{{ vote.description }}</p>
                    <h4><span><i class="fas fa-thumbs-up"></i>40</span> interested</h4>
                    <h4><span><i class="fas fa-thumbs-down"></i>15</span> not interested</h4>
                </div>
            </div>
                </a>
            {% endfor %}


    </div>
{% endblock %}