home/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('', views.home, name='home'),
        path('signup', views.sign_up, name='signup'),
        path('signin', views.sign_in, name='signin'),

]

trips/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('', views.trips_main, name='trips'),
        path('t', views.trips, name='Trips'),
        path('filter', views.trips_form, name='Trips_form'),
]

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.users, name='users'),
    path('/logout', views.signout, name='signout')
]

votes/urls.py
from django.urls import path
from . import views

urlpatterns= [

        path('', views.votes, name='votes'),
]

agencies/models.py
from django.db import models


class Agencies(models.Model):
    agency_id = models.AutoField(db_column='Agency_id', primary_key=True)
    name = models.CharField(max_length=45)
    address = models.CharField(db_column='Address', max_length=45)
    e_mail = models.CharField(db_column='E-mail', max_length=45)
    commercial_id = models.CharField(max_length=45)
    bio = models.CharField(max_length=45)
    promo_code = models.CharField(db_column='promo-code', max_length=45)
    rate = models.CharField(db_column='Rate', max_length=45)
    photo_url = models.TextField(db_column='photo_URL')

    class Meta:
        managed = False
        db_table = 'agencies'


class Phones(models.Model):
    agency = models.ForeignKey(Agencies, models.DO_NOTHING, db_column='Agency_id')
    phone = models.CharField(max_length=13, primary_key=True)

    class Meta:
        managed = False
        db_table = 'phones'
        unique_together = (('agency', 'phone'),)


class Users(models.Model):
    user_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    e_mail = models.CharField(db_column='e-mail', max_length=45, blank=True, null=True)
    phone = models.CharField(max_length=11, blank=True, null=True)
    city = models.CharField(max_length=45)

    class Meta:
        managed = False
        db_table = 'users'


class Follows(models.Model):
    user = models.ForeignKey('Users', models.DO_NOTHING, primary_key=True)
    agency = models.ForeignKey(Agencies, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'follows'
        unique_together = (('user', 'agency'),)

agency/models.py
from django.db import models


class Agencies(models.Model):
    agency_id = models.AutoField(db_column='Agency_id', primary_key=True)
    name = models.CharField(max_length=45)
    address = models.CharField(db_column='Address', max_length=45)
    e_mail = models.CharField(db_column='E-mail', max_length=45)
    commercial_id = models.CharField(max_length=45)
    bio = models.CharField(max_length=45)
    promo_code = models.CharField(db_column='promo-code', max_length=45)
    rate = models.CharField(db_column='Rate', max_length=45)
    photo_url = models.TextField(db_column='photo_URL')

    class Meta:
        managed = False
        db_table = 'agencies'


class Phones(models.Model):
    agency = models.ForeignKey(Agencies, models.DO_NOTHING, db_column='Agency_id')
    phone = models.CharField(max_length=13, primary_key=True)

    class Meta:
        managed = False
        db_table = 'phones'
        unique_together = (('agency', 'phone'),)


class Users(models.Model):
    user_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    phone = models.CharField(max_length=11, blank=True, null=True)
    city = models.CharField(max_length=45)

    class Meta:
        managed = False
        db_table = 'users'


class Follows(models.Model):
    user = models.ForeignKey('Users', models.DO_NOTHING, primary_key=True)
    agency = models.ForeignKey(Agencies, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'follows'
        unique_together = (('user', 'agency'),)


class Trips(models.Model):
    trip_id = models.AutoField(db_column='Trip_id', primary_key=True)  # Field name made lowercase.
    agency = models.ForeignKey(Agencies, models.DO_NOTHING, db_column='Agency_id')  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=50)  # Field name made lowercase.
    from_location = models.CharField(db_column='From_Location', max_length=45)  # Field name made lowercase.
    to_location = models.CharField(db_column='To_Location', max_length=45)  # Field name made lowercase.
    date_from = models.DateTimeField(db_column='Date_From')  # Field name made lowercase.
    date_to = models.DateTimeField(db_column='Date_To')  # Field name made lowercase.
    deadline = models.DateTimeField(db_column='Deadline')  # Field name made lowercase.
    meals = models.CharField(db_column='Meals', max_length=45)  # Field name made lowercase.
    price = models.FloatField(db_column='Price')  # Field name made lowercase.
    description = models.TextField(db_column='Description')  # Field name made lowercase.
    views = models.PositiveIntegerField(db_column='Views')  # Field name made lowercase.
    rate = models.FloatField(db_column='Rate')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'trips'


class TripPhotos(models.Model):
    trip = models.ForeignKey('Trips', models.DO_NOTHING, db_column='Trip_id', primary_key=True)
    url = models.TextField(db_column='URL')

    class Meta:
        managed = False
        db_table = "trip_photos'"


class GoingTo(models.Model):
    user = models.ForeignKey('Users', models.DO_NOTHING, db_column='User_id', primary_key=True)
    trip = models.ForeignKey('Trips', models.DO_NOTHING, db_column='Trip_id')

    class Meta:
        managed = False
        db_table = 'going_to'
        unique_together = (('user', 'trip'),)

class Vote(models.Model):
    vote_id = models.AutoField(db_column='Vote_id', primary_key=True)  # Field name made lowercase.
    agency = models.ForeignKey(Agencies, models.DO_NOTHING, db_column='Agency_id')  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=45)  # Field name made lowercase.
    description = models.TextField(db_column='Description')  # Field name made lowercase.
    photo_url = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'vote'

agencies/views.py
from django.shortcuts import render, redirect
from .models import *


def agencies(request):
    company = Agencies.objects.all()
    query = request.GET.get("q")
    if query:
        company = Agencies.objects.filter(name__icontains=query)
    if "user_id" in request.session != None:
        user_id = request.session['user_id']
        follows = Follows.objects.filter(user_id=user_id)
        followed = get_follow(company, follows)
        obj = {
            "agency": company,
            "follow": followed,
        }

    else:

        obj = {
            "agency": company,
        }
    return render(request, "agencies.html", obj)


def main(request):
    agencies(request)
    return render(request, 'main.html')


def follow(request):
    if request.method == "POST":
        user_id = request.session['user_id']
        agency_id = request.POST['btnFollow']
        Follows.objects.create(user_id=user_id, agency_id=agency_id)
    return redirect(agencies)


def un_follow(request):
    if request.method == "POST":
        user_id = request.session['user_id']
        agency_id = request.POST['btnUnfollow']
        Follows.objects.filter(user_id=user_id, agency_id=agency_id).delete()
    return redirect(agencies)


def get_follow(agencies_follow, follows):
    agency_follow = []
    for a in agencies_follow:
        followed = False
        if follows.filter(agency_id=a.agency_id).exists():
            followed = True
        following = {
                'agency': a.agency_id,
                'follow': followed
            }
        agency_follow.append(following)
    return agency_follow

agency/views.py
import datetime
from django.shortcuts import render
from .models import *


def agency(request, agency_name):
    agency_id = Agencies.objects.get(name__icontains=agency_name).agency_id

    q = request.GET.get('button')

    if q == 'available':
        obj = available(agency_id)
        return render(request, "agency_trips.html", obj)

    elif q == 'votes':
        obj = agency_votes(agency_id)
        return render(request, 'agency_votes.html', obj)

    elif q == 'account':
        obj = agency_info(agency_id)
        return render(request, 'agency_info.html', obj)

    else:
        obj = history(agency_id)
        return render(request, "agency_trips.html", obj)


def available(agency_id):
    company = Agencies.objects.get(agency_id=agency_id)
    trip = Trips.objects.filter(agency_id=agency_id, deadline__gt=datetime.date.today())
    for t in trip:
        t.duration = t.date_to.date() - t.date_from.date()

    active = 'active'
    inactive = 'inactive'
    obj = {
        "agency": company,
        "trips": trip,
        "history": inactive,
        "available": active,
    }
    return obj


def history(agency_id):
    company = Agencies.objects.get(agency_id=agency_id)
    trip = Trips.objects.filter(agency_id=agency_id, deadline__lt=datetime.date.today()).order_by('deadline')
    for t in trip:
        t.duration = t.date_to.date() - t.date_from.date()

    active = 'active'
    inactive = 'inactive'
    obj = {
        "agency": company,
        "trips": trip,
        "history": active,
        "available": inactive,
    }
    return obj


def agency_votes(agency_id):
    company = Agencies.objects.filter(agency_id=agency_id)[0]
    votes = Vote.objects.filter(agency_id=agency_id)
    obj = {
        "votes": votes,
        "agency": company,
    }
    return obj


def agency_info(agency_id):
    company = Agencies.objects.get(agency_id=agency_id)
    obj = {
        "agency": company,
    }
    return obj

home/views.py
import datetime
from django.shortcuts import render ,redirect
from .models import *
from cryptography.fernet import Fernet
import base64
from Exoduss import settings
from django.http import HttpResponse


def home(request):
    votes = Vote.objects.all().order_by('vote_id').reverse()[:0]

    trips = Trips.objects.raw('SELECT t.*, COUNT(g.`User_id`) AS going_to '
                              'FROM `Exodus`.`Trips` t '
                              'LEFT JOIN `Exodus`.`going_to` g ON t.`trip_id` = g.`Trip_id` '
                              'Where t.`Deadline` > CURDATE() GROUP BY t.`Trip_id` '
                              'ORDER BY going_to DESC '
                              'LIMIT 4;')

    agencies = Agencies.objects.raw('SELECT a.*, COUNT(f.`agency_id`) AS followers '
                                    'FROM `Exodus`.`Agencies` a '
                                    'LEFT JOIN `Exodus`.`Follows` f ON a.`Agency_id` = f.`agency_id` '
                                    'GROUP BY a.`Agency_id` '
                                    'ORDER BY followers DESC '
                                    'LIMIT 4;')
    most_trips = Trips.objects.filter(deadline__gt=datetime.datetime.today()).order_by('trip_id').reverse()[:4]
    if "user_id" in request.session != None:
        user_id = request.session['user_id']
        user = Users.objects.filter(user_id=user_id)[0]
        obj = {
            'votes': votes,
            'most_going': trips,
            'agencies': agencies,
            'most_trips': most_trips,
            'user': user

        }
    else:
        user = 0
        obj = {
            'votes': votes,
            'most_going': trips,
            'agencies': agencies,
            'most_trips': most_trips,
            'user': user

        }
    return render(request, 'home.html', obj)


def sign_up(request):
    name = request.POST["username"]
    email=request.POST["email"]
    phone=request.POST["number"]
    city = request.POST["city"]
    password = request.POST["psw"]
    re_password = request.POST["repsw"]

    unique_mail = Users.objects.filter(e_mail__iexact=email)
    print(unique_mail)
    if not unique_mail:
        if password == re_password:
            # get the key from settings
            cipher_suite = Fernet(settings.ENCRYPT_KEY)  # key should be byte
            # #input should be byte, so convert the text to byte
            encrypted_text = cipher_suite.encrypt(password.encode('ascii'))
            # encode to urlsafe base64 format
            encrypted_text = base64.urlsafe_b64encode(encrypted_text).decode("ascii")
            Users.objects.create(name=name, e_mail=email, password=encrypted_text, phone=phone, city=city)
            return redirect(home)
        else:
            return HttpResponse("PASSWORD NOT COMPATIBLE")
    else:
        return HttpResponse("EMAIL ALREADY EXISTS")


def sign_in(request):
    if request.method == "POST":
        if request.method == "POST":
            email = request.POST["email"]
            psw = request.POST["psw"]
            insure = Users.objects.filter(e_mail__iexact=email)
            if not insure:
                return HttpResponse("WRONG E-MAIL OR PASSWORD")



            else:

                user = Users.objects.get(e_mail__iexact=email)
                passw = user.password
                txt = base64.urlsafe_b64decode(passw)
                cipher_suite = Fernet(settings.ENCRYPT_KEY)
                decoded_text = cipher_suite.decrypt(txt).decode("ascii")
                if decoded_text == psw:
                    request.session['user_id'] = user.user_id

                    return redirect(home)
                else:
                    return HttpResponse("WRONG E-MAIL OR PASSWORD")

trips/views.py
from django.shortcuts import render
from .models import *
from .forms import SearchForm
from django.db.models import Q


def trips_main(request):
    return render(request, 'trips_main.html')


def trips(request):
    trip = Trips.objects.all()
    form = SearchForm()

    if request.POST.get('select', None):
        sort_option = request.POST.get('select')
        trip = trip.order_by(sort_option)

    for t in trip:
        t.duration = t.date_to.date() - t.date_from.date()

    obj = {
        'trips': trip,
        'form': form,
    }

    return render(request, 'trips.html', obj)


def trips_form(request):
    if request.method == 'GET':
            form = SearchForm(request.GET)
            if form.is_valid():
                city = form.cleaned_data['Destination']
                date_from = form.cleaned_data['Date']
                date_to = form.cleaned_data['Date2']
                price = form.cleaned_data['price']
                meals = form.cleaned_data['meals']
                agency = form.cleaned_data['agency']
                filters = []
                if agency != '':
                    agencyiesIDS = Agencies.objects.filter(name__icontains=agency)
                    ids = []
                    for agencyID in agencyiesIDS:
                        idd = agencyID.agency_id
                        ids.append(idd)
                    agencyfilter = Trips.objects.filter(agency_id__in=ids)
                    filters.append(agencyfilter)
                if date_from is not None and date_to is not None:
                    datefilter = Trips.objects.filter(Q(date_from__gte=date_from) & Q(date_to__lte=date_to))
                    filters.append(datefilter)
                elif date_from is not None:
                    date_fromfilter = Trips.objects.filter(date_from__gte=date_from)
                    filters.append(date_fromfilter)
                elif date_to is not None:
                    date_tofilter = Trips.objects.filter(date_to__lte=date_to)
                    filters.append(date_tofilter)
                if price is not None:
                    price_filter = Trips.objects.filter(price__lte=price)
                    filters.append(price_filter)

                if city is not '':
                    cityfilter = Trips.objects.filter(to_location__icontains=city)
                    filters.append(cityfilter)
                if meals in ['fullboard', 'halfboard']:
                    mealfilter=Trips.objects.filter(meals__exact=meals)
                    filters.append(mealfilter)
                if len(filters) > 0:
                    trips = filters[0]
                    for Filter in filters:
                        trips = trips | Filter

                    context = {
                        'trips': trips,
                        'form': form,
                    }
                    return render(request, 'trips.html', context)

votes/views.py
from django.shortcuts import render
from .models import Vote, Response, Agencies

def votes(request):

    agencies = Agencies.objects.all()
    votes_all = Vote.objects.all()
    responses = Response.objects.all()

    context = {
        'votes_all': votes_all,
        'responses': responses,
        'agencies': agencies,
    }

    return render(request, 'votes.html', context)

templates/agencies.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Exodus -> Agencies</title>
    <!-- <link rel="stylesheet" href="css/bootstrap.min.css"/> -->
    <link rel="stylesheet" href="{% static 'css/font-awesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/exo-2.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{%  static 'css/agencies.css' %}">

  </head>
  <body>
  <div class="contain">
  <!-- Start Agencies -->
      <div class="agencies">
          <div class="search-vote">
                <form method='GET' action=''>
                    <input type="text" name="q" value="{{ request.GET.q }}" placeholder="Search In Agencies...">
                    <button type="submit" value="Search">search</button>
                </form>
            </div>
          <div class="clear"></div>
          {% for a in agency %}
              <div class="agency-card">
                <a href="{% url 'agencies' %}/{{ a.name }}">
                  <img src="{{ a.photo_url }}" alt="">
                  <h3> {{ a.name }}</h3>
                </a>
                  {% for f in follow %}
            {% if f.agency == a.agency_id %}
                {% if f.follow %}
                    <form method="post" action="unfollow">
                    {% csrf_token %}
                        <div class="follow-btn">
                            <span>{{ a.follows_set.count }}</span>
                            <button name="btnUnfollow" type="submit" value="{{ a.agency_id }}">Unfollow</button>
                        </div>
                    </form>
                {% else %}
                    <form method="post" action="follow">
                    {% csrf_token %}
                    <div class="follow-btn">
                            <span>{{ a.follows_set.count }}</span>
                            <button name="btnFollow" type="submit" value="{{ a.agency_id }}">Follow</button>
                        </div>
                    </form>
            {% endif %}
            {% endif %}
        {% endfor %}
              </div>
          {% endfor %}

          <!-- End Agencies -->
         </div>
    </div>

  </body>
</html>

templates/agency.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
          <title>{{ agency.name }}</title>
    <link rel="stylesheet" href="{% static 'css/font-awesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/exo-2.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/agency.css' %}">
  </head>
  <body>

    <div class="contain">
      <!-- Start Tabs Panel -->
      <div class="tabs-panel">
        <div class="prof-intro">
          <img src="{{ agency.photo_url }}" alt="">
          <h3>{{ agency.name }}</h3>
          <span><i class="fas fa-star"></i>{{ agency.rate }}</span>
          <span><i class="fas fa-users"></i>{{ agency.follows_set.count }}</span>
          <div class="clear"></div>
          <button class="" type="button" name="button">follow</button>
        </div>
        <div class="prof-tabs">
          <form method="get" action="">
              <button name="button" value="trips" type="submit" class="active" data-id="tab1">trips<i class="fas fa-chevron-right"></i></button>
              <button name="button" value="votes" type="submit" data-id="tab2">votes<i class="fas fa-chevron-right"></i></button>
              <button name="button" value="account" type="submit" data-id="tab3">account<i class="fas fa-chevron-right"></i></button>
          </form>
        </div>
      </div>
      <!-- End Tabs Panel -->

      <!-- Start Tab Details -->
      <div>
      {% block content %}
        <!--

        -->
      {% endblock %}
      </div>
      <!-- End Tab Details -->
    </div>

    <div class="clear"></div>

    <script src="{% static 'js/JQuery%20(v3.2.1).js' %}"></script>
    <!-- <script src="js/bootstrap.min.js"></script> -->
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

templates/sign up.html
<html>

<title></title>

<body>
<main role="main" class="container">
    {% csrf_token %}
    <form method="POST">
        {{ form.as_p }}
        <button value="submit" class="btnsignup">Submit</button>
        </main>
    </form>

</body>
</html>

templates/trips.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Exodus -> Trips</title>
    <link rel="stylesheet" href="{% static 'css/font-awesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/exo-2.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/trips.css' %}">
  </head>
  <body>

    <div class="contain">
      <!-- Start Filter -->
      <div class="filter">
        <h2>find your trip</h2>
        <form action="filter" method="get" name="form">
          {{ form }}
          <button type="submit" name="form"><i class="fas fa-filter"></i>filter</button>
        </form>

      </div>
      <!-- End Filter -->

      <!-- Start Trips -->
      <div class="trips">
      <div class="sort">
        <form action="" method="post">
            {% csrf_token %}
            <select id="sort" name="select">
                <option value="1">sort by...</option>
                <option value="price">price</option>
                <option value="date_from">date</option>
            </select>
            <i class="fas fa-arrow-up"></i>
            <i class="fas fa-arrow-down"></i>
            <button type="submit" name="button">sort</button>
        </form>
      </div>
        {% for t in trips %}
{#            <a href="{% url 'trip-page' %}/{{ t.name }}">#}
          <div class="trip-post">
            <div class="trip-img">
              <img src="{{ t.tripphotos_set.all.0.url }}" alt="">
              <div class="overlay">
                <button class="learn-more" type="button" name="button">learn more</button>
              </div>
            </div>
            <div class="trip-info">
              <h2>{{ t.name }}</h2>
              <h2>{{ t.agency.name }}</h2>
              <h4><span>price</span>{{ t.price }}</h4>
              <h4><span>date</span>{{ t.date_from|date:"d/m/Y" }}</h4>
              <h4><span>duration</span> {{ t.duration.days }} days</h4>
              <h4><span>meals</span>{{ t.meals }}</h4>

              <h4><span><i class="fas fa-plane"></i>going</span>{{ t.goingto_set.count }}</h4>
              <h4><span><i class="far fa-eye"></i>views</span>{{ t.views }}</h4>
            </div>
          </div>
{#        </a>#}
        {% endfor %}
      </div>
      <!-- End Trips -->
    </div>

    <div class="clear"></div>

    <script src="{% static 'js/JQuery%20(v3.2.1).js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

templates/user.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>User</title>
    <link rel="stylesheet" href="{% static 'css/font-awesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/exo-2.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/user.css' %}">
  </head>
  <body>

    <div class="contain">
      <!-- Start Tabs Panel -->
      <div class="tabs-panel">
        <div class="prof-intro">
          <img src="{{ user.photo_url }}" alt="">
          <h3>{{ user.name }}</h3>
        </div>

        <div class="prof-tabs">
          <button class="active" type="submit" data-id="tab1">trips</button>
          <button type="submit" data-id="tab2">agencies</button>
          <button type="submit" data-id="tab3">account</button>
        </div>

        <a href="{% url 'signout' %}">sign out</a>
      </div>
      <!-- End Tabs Panel -->

      <!-- Start Tab Details -->
      <div>
        <div id="tab1" class="tab-details active">
          <div class="my-trips-tabs">
            <form data-id="history" class="active"><button type="button" name="button">history</button></form>
            <form data-id="saved"><button type="button" name="button">available</button></form>
          </div>
          <div>
            <div id="history" class="post-contain active">

                {% for trip in trips %}
                    <a href="trip-page.html">
                    <div class="post">
                  <div class="post-img">
                    <img src="{{ trip.trip.tripphotos_set.0 }}" alt="">
                    <div class="overlay">
                      <button class="learn-more" type="button" name="button">review</button>
                    </div>
                  </div>
                  <div class="post-info">
                    <h2>{{ trip.trip.name }}</h2>
                    <h2>{{ trip.trip.agency.name }}</h2>
                    <h4><span>price</span>{{ trip.trip.price }}</h4>
                    <h4><span>date</span>{{ trip.trip.date_from| date:'d/n/Y' }}</h4>
                    <h4><span>duration</span> 5 days</h4>
                    <h4><span>meals</span>{{ trip.trip.meals }}</h4>

                    <h4><span><i class="fas fa-plane"></i>going</span>{{ trip.trip.goingto_set.count }}</h4>
                    <h4><span><i class="far fa-eye"></i>views</span>{{ trip.trip.views }}</h4>
                  </div>
                </div>
                    </a>
                {% endfor %}

            </div>

            <div id="saved" class="post-contain">
              <a href="trip-page.html">
                <div class="post">
                  <div class="post-img">
                    <img src="photos/header-4.jpg" alt="">
                    <div class="overlay">
                      <button class="learn-more" type="button" name="button">learn more</button>
                    </div>
                  </div>
                  <div class="post-info">
                    <h2>cairo, giza</h2>
                    <h2>lucky tour</h2>
                    <h4><span>price</span> 1200</h4>
                    <h4><span>date</span> 2 / 5 / 2019</h4>
                    <h4><span>duration</span> 5 days</h4>
                    <h4><span>meals</span> fullboard</h4>

                    <h4><span><i class="fas fa-plane"></i>going</span> 35</h4>
                    <h4><span><i class="far fa-eye"></i>views</span> 80</h4>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </div>
        <!-- //////////////////////////////////// -->
        <div id="tab2" class="tab-details">
          <div class="search-agency">
            <input type="text" name="" value="" placeholder="Search In Agencies...">
            <button type="button" name="button">search</button>
          </div>

            {% for agency in agencies %}
                <a href="{% url 'agencies' %}/{{ agency.agency.name }}">
                <div class="post">
              <div class="post-img">
                <img src="{{ agency.agency.photo_url }}" alt="">
                <div class="overlay">
                  <button class="learn-more" type="button" name="button">agency page</button>
                </div>
              </div>
              <div class="post-info">
                <h2>{{ agency.agency.name }}</h2>
                <h2>{{ agency.user.follows_set.count }} followers</h2>
                <div class="clear"></div>
                <p>{{ agency.agency.bio }}</p>

                <h4><span><i class="fas fa-star"></i>rating</span>{{ agency.agency.rate }}</h4>
                <h4><span><i class="fas fa-plane"></i>trips</span>{{ agency.agency.trips_set.count }}</h4>
              </div>
            </div>
            </a>
            {% endfor %}



        </div>
        <!-- //////////////////////////////////// -->
        <div id="tab3" class="tab-details">
          <div class="user-info">
            <img src="photos/others/user-avatar.png" alt="">
            <form class="" action="index.html" method="post">
              <div>
                <label>username</label>
                <h3>{{ user.name }}</h3>
              </div>
              <div>
                <label>City</label>
                <h3>{{ user.city }}</h3>
              </div>
              <div>
                <label>phone</label>
                <h3>{{ user.phone }}</h3>
              </div>
            </form>
            <button type="button" onclick="document.getElementById('edit-info').style.display='block'">edit</button>
            <button type="button" onclick="document.getElementById('delete-confirm').style.display='block'">delete account</button>
          </div>
        </div>
      </div>
      <!-- End Tab Details -->
    </div>

    <div class="clear"></div>

    <script src="{%  static 'js/JQuery%20(v3.2.1).js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>